Hotel Rental/Controllers/HomeController.cs
using Hotel.Core.Interface;
using Hotel.Core.ViewModel;
using Hotel_Rental.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.Threading.Tasks;

namespace Hotel_Rental.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public IProductService _productService;
        public ICategoryService _categoryService;

        public HomeController(ILogger<HomeController> logger, IProductService productService, ICategoryService categoryService)
        {
            _logger = logger;
            _productService = productService;
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Index()
        {
            var userProduct = await _productService.;
            //userProduct.MostPickerProducts = await _productService.GetAllProductsByCategoryIdAsync(userProduct.Categories[0].Id);
            return View(userProduct);
        }

        public IActionResult Details()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Hotel Rental/Controllers/LoginController.cs
using Hotel.Core.Interface;
using Hotel_Rental.Models;
using Microsoft.AspNetCore.Mvc;

namespace Hotel_Rental.Controllers
{
    public class LoginController : Controller
    {
        public readonly IUserService _userService;
        public LoginController(IUserService userService)
        {
            _userService = userService;
        }
        [HttpGet]
        public IActionResult Index()
        {
            
            return View();
        }
        [HttpPost]
        public IActionResult Index(User user)
        {
            //if (user != null)
            //{
            //    return RedirectToAction("Index", "Home");
            //}
            //return View();

            if(ModelState.IsValid)
            {
               var userExist = _userService.Login(user.Email, user.Password).GetAwaiter().GetResult();
                if(userExist)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("error", "Invalid credentials");
                }
                return View();
            }
            else
            {
                ModelState.AddModelError("error", "Not registered");
            }
            return View();
        }

    }
}

Hotel Rental/Controllers/SignUpController.cs
using Hotel.Core.Interface;
using Hotel_Rental.Models;
using Microsoft.AspNetCore.Mvc;

namespace Hotel_Rental.Controllers
{
    public class SignUpController : Controller
    {
        public readonly IUserService _userService;
        public SignUpController(IUserService userService)
        {
            _userService = userService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(User user)
        {
            //if (user != null)
            //{
            //    if (!Validation.CheckEmail(user.Email))
            //    {
            //        return View();
            //    }
            //    if (!Validation.CheckPassword(user.Password))
            //    {
            //        return View();
            //    }
            //    _userService.RegisterUser(user).GetAwaiter();
            //    return RedirectToAction("Index", "Login");
            //}
            //return View();

            if (ModelState.IsValid)
            {
                _userService.RegisterUser(user).GetAwaiter();
                return RedirectToAction("Index", "Login");
            }
            else
            {
                ModelState.AddModelError("error", "Not registered");
            }
            return View();  
        }
    }
}

Hotel Rental/Views/Home/Details.cshtml
<div class="detail_container">
    <div>
         @*//Heading Section*@
        <p class="home">Home     /     House Details</p>
        <h1 class="vilage">Village Angga</h1>
        <p class="subvil">Bogor, Indonesia</p>
    </div>

    <div class="eye" flex: column>
        <div class="eye1">
            <img src="~/images/Image folder/detail-img1.png" alt="marketing illustration" class="det1">
        </div>
        <div class="eye2">
            <div class="y1">
               <img src="~/images/Image folder/detail-img2.png" alt="building" class="det2" />
            </div>
            <div class="y2">
              <img src="~/images/Image folder/detail-img3.png" alt="building" class="det3" />
            </div>

        </div>
    </div>

    <div class="details">
        <div class="">
            <h4 class="about">About the place</h4>
            <p class="abt">Minimal techno is a minimalist subgenre of techno music.
                It is characterized by a stripped-down aesthetic that
                exploits the use of repetition and understated development.
                Minimal techno is thought to have been originally developed
                in the early 1990s by Detroit-based producers Robert Hood and Daniel Bell.</p><br />
                <br />
                <p class="such">Such trends saw the demise of the soul-infused techno
                    that typified the original Detroit sound.
                    Robert Hood has noted that he and Daniel Bell
                    both realized something was missing
                    from techno in the post-rave era.</p><br />
                    <br />
                    <p class="design">Design is a plan or specification for the construction of an object
                        or system or for the implementation of an activity or process, or 
                        the result of that plan or specification in the form of a prototype,
                        product or process. The national agency for design:
                        enabling Singapore to use design for economic growth
                        and to make lives better.</p>
        </div>
        <div class="">
           <h5  class="startbooking">Start Booking</h5>
           <h3 class="per">$280 per night</h3>
           <p class="how">How long you will stay?</p>
           <div class="nit">
           <button type="button" class="red">- </button>
            <div class="nights">2 nights </div>
             <button type="button" class="green">+ </button>
             </div>
             <p class="pic">Pick a Date</p>
             <button type="button"><img src="~/images/Image folder/detail-imgt.png" alt="button"  class="purple" /></button>
             @*<div class="jan">20 Jan - 22 Jan</div>
             <div class="usd">You will pay $480 USD per 2 nights</div>
            
            <button type="button" class="book">Continue to Book </button>*@

        
        </div>

    </div>

    <div class="treasures">
        <p class="tre">Treasure to Choose</p>
       @* @{
            foreach(var item in .....)
        }*@
        <div>
            <img src="~/images/Image folder/detail-img4.png" alt="building" class="det4" />
        </div>
        <div>
            <img src="~/images/Image folder/detail-img5.png" alt="building" class="det5" />
        </div>
        <div>
            <img src="~/images/Image folder/detail-img6.png" alt="building" class="det6" />
        </div>
        <div>
            <img src="~/images/Image folder/detail-img7.png" alt="building" class="det7" />
        </div>
    </div>


    <div class="happyfamily">
        <div class="">
            <img src="~/images/Image folder/detail-img8.png" alt="building" class="pict" />
        </div>
        <div>
            <p class="hap">Happy Family</p>
        </div>
        <div class="stars">
            @* <img src="~/images/Image folder/Star 1.png" alt="building" class="st" />
              <img src="~/images/Image folder/Star 1.png" alt="building" class="sta" />*@
               <i class="star">&#9734;&#9734;&#9734;&#9734;&#9734;</i>
               <p class="as">As a wife I can pick a great trip with
                  my own lovely family ... thank you!</p>
                  <p class="an">Anggi, Product Designer</p>
                  <a class="re" href="#"> Read Their Story</a>
        </div>

    </div>


</div>

Hotel Rental/Views/Login/Index.cshtml
@model User

@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
}
    <div class="center">
      <h1>Login</h1>
      <form method="post" asp-action="index" asp-controller="login">
          <div asp-validation-summary="All" style="color:aqua"></div>
        <div class="txt_field">
          <input asp-for="Email">
          <span></span>
          @*<label>Username</label>*@
          <label>Email</label>
        </div>
        <div class="txt_field">

            @*<input asp-for="Email" type="email" placeholder="Email">
            <span asp-validation-for="Email" style="color: red" ></span>*@

            @*<input asp-for="Password" type="password" placeholder="Password">
            <span asp-validation-for="Password" style="color: red"></span>*@

          <input asp-for="Password">
          <span></span>
          <label>Password</label>
        </div>
        <div class="pass">Forgot Password?</div>
        <input type="submit" value="Login">
        <div class="signup_link">
          Not a member? <a asp-action="index" asp-controller="SignUp">Signup</a>
        </div>
      </form>
    </div>

Hotel Rental/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hotel Site</title>
   @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
   <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar">
               <div class="site-logo">
                     <a class="navbar-brand" asp-area="" asp-controller="staycation" asp-action="Index">Staycation</a>
                </div>
               <div class="header-container">
                
               
                @*<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>*@
                <div class="navbar-collapse site-nav-menu">
                    <ul class="navbar-nav ">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="browse by" asp-action="Privacy">Browse by</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="storie" asp-action="Privacy">Stories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="agents" asp-action="Privacy">Agents</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Details">Details</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @*SECTION 1- Vacation Pleasure*@

    

    <div class="container1">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    

    @*<footer>
  <p>Author: Hege Refsnes<br>
  <a href="mailto:hege@example.com">hege@example.com</a></p>
</footer>

</body>
</html>*@
    
    <footer class="footer text-muted">

        <div class="footer-list-container">
            <div>
                <h1 class="stay">Staycation</h1>
                <p class="we">We kaboom your beauty holiday<br />
                           instantly and memorable.</p>
            </div>
            <div >
                <h1 class="begin">For Beginners</h1>
                <p class="new">New Account
                   Start Booking<br /> a Room 
                   Use Payments.
             </p>
             </div>
             <div>
                 <h1 class="ex">Explore Us</h1>
                    <p class="our"> Our Careers<br />
                        Privacy
                        Terms & Conditions
                    </p>
             </div>
             <div>
                 <h1 class="con">Contact Us</h1>
                 <p class="sup">support@staycation.id<br />
                    021 - 2208 - 1996<br />
                   Staycation, Kemang, Jakarta</p>
             </div>
            </div>
        
            <div class="foot"> @*id="footer"*@
            &copy; 2022 - Hotel_Rental . All rights reserved . Staycation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
   @* <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)*@
</body>
</html>

Hotel Rental/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Responsive Login Form | Olaoluwa Esan</title>
    <link rel="stylesheet" href="~/css/login.css">
    <script type="text/javascript" src="script.js"></script>
   
  </head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

Hotel Rental/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script type="text/javascript" src="signup.js"></script>
<link rel="stylesheet" href="~/css/SignUp.css">
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

Hotel Rental/Views/SignUp/Index.cshtml
@using Hotel_Rental.Models
@model User
@{
    ViewBag.Title = "Registration Page";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

 
 
<section class="section-log-in">
    <div class="container">
  
      <div class="choices-container" id="choices-container">
       
  
        <div class="forms-container">
          <form class="form form-sign-up" method="post" asp-action="index">
              <div asp-validation-summary="ModelOnly" style="color: red;"></div>
            <h3 class="text-form">Sign Up</h3>
            <input asp-for="FullName" type="text" placeholder="Full Name">
            <span asp-validation-for="FullName" style="color: red"></span>
            <input asp-for="Email" type="email" placeholder="Email">
            <span asp-validation-for="Email" style="color: red" ></span>
            <input asp-for="Password" type="password" placeholder="Password">
            <span asp-validation-for="Password" style="color: red"></span>
            <input class="btn btn-sign-up" type="submit" value="SignUp">
            
          </form>
        </div>
      </div>
  
    </div>
  </section>